### ISSUE TITLE
socks5 代理错误

### ISSUE THREAD

**Issue by antiwj** [3003h/Eros-FE#363]
### 复现步骤 / Steps to reproduce

设置代理模式为socks5，之后刷新app界面提示加载失败，代理用户名或密码错误。
代理经过多次测试是能用的。

### 预期行为 / Expected behaviour

同样此代理配置，使用shadowrocket的系统代理后，app界面能正常加载出来。

### 实际行为 / Actual behaviour

Socks proxy invalid username or password
![1](https://github.com/3003h/Eros-FE/assets/127014396/7e5b6783-e41e-4e68-8267-05000c5a590d)

### Eros-FE 版本号 / Eros-FE version code

1.6.1

### Eros-FE CI 版本 / Eros-FE CI version

https://github.com/3003h/Eros-FE/actions/runs/8538172709

### 平台 / Platform

iOS

### 系统版本 / System version

iOS 17.5.1

### 设备型号 / Device model

iPhone se2

### SoC 型号 / SoC model

A13

### 应用日志 / App logs

[E] HttpException{_message: Socks proxy invalid username or password, _code: null, _data: null}
[E] #0      getGallery (package:eros_fe/network/request.dart:170)
[E] <asynchronous suspension>
[E] #1      SearchFetchListClient.fetch (package:eros_fe/pages/tab/fetch_list.dart:70)
[E] <asynchronous suspension>
[E] #2      CustomSubListController.fetchData (package:eros_fe/pages/tab/controller/group/custom_sublist_controller.dart:74)
[E] <asynchronous suspension>
[E] #3      TabViewController.firstLoad (package:eros_fe/pages/tab/controller/tabview_controller.dart:168)
[E] <asynchronous suspension>
[E] #4      CustomSubListController.firstLoad (package:eros_fe/pages/tab/controller/group/custom_sublist_controller.dart:37)
[E] <asynchronous suspension>
[E] 
![image](https://github.com/3003h/Eros-FE/assets/127014396/1447ecc3-e2e5-48b4-b342-4f5b97a9a775)

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/3003h/Eros-FE/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/3003h/FEhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/3003h/Eros-FE/actions/workflows/release.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/3003h/FEhViewer/actions/workflows/release.yml)

**Comment by wei-jun7** [comment]
我感觉是代理出错连不进里站但是表展是可以的

**Comment by wei-jun7** [comment]
一直默认设置也没有搞过其他，看了一下输出日志，他是能获得请求成功的，我也不是很清楚哪里出了问题
